services:
  mysql:
    image: mysql:8.0.41
    ports:
      - '3300:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  gate-simulator:
    build:
      context: ./gate-simulator
      dockerfile: Dockerfile
    image: gate-simulator:1.0
    ports:
      - '9999:9999'
